-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 18:35:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbProjektor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbProjektor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbProjektor` DEFAULT CHARACTER SET utf8 ;
USE `dbProjektor` ;

-- -----------------------------------------------------
-- Table `dbProjektor`.`StudentGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`StudentGroups` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`StudentGroups` (
  `idStudentGroup` INT NOT NULL AUTO_INCREMENT,
  `RokRozpoczecia` DATE NOT NULL,
  `Nazwa_StudentGrups` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudentGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`StudentWykladowca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`StudentWykladowca` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`StudentWykladowca` (
  `id_StudentWykladowca` INT NOT NULL,
  `id_StudentGroups` INT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Nr_Indexu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_StudentWykladowca`),
  INDEX `fk_Studenci_StudentGrups1_idx` (`id_StudentGroups` ASC),
  CONSTRAINT `fk_Studenci_StudentGrups1`
    FOREIGN KEY (`id_StudentGroups`)
    REFERENCES `dbProjektor`.`StudentGroups` (`idStudentGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Przedmiot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Przedmiot` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Przedmiot` (
  `id_Przedmiot` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Przedmiot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Pytania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Pytania` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Pytania` (
  `id_Pytania` INT NOT NULL,
  `Tekst Pytania` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Pytania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Odopwiedzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Odopwiedzi` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Odopwiedzi` (
  `id_Odpowiedzi` INT NOT NULL,
  `Odpowiedz` VARCHAR(45) NOT NULL,
  `Czy_prawidłowa` TINYINT NOT NULL,
  PRIMARY KEY (`id_Odpowiedzi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Testy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Testy` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Testy` (
  `id_Test` INT NOT NULL AUTO_INCREMENT,
  `Pytania_idPytania` INT NOT NULL,
  `Odopwiedzi_idPytania` INT NOT NULL,
  `Id_test_grupa` INT NOT NULL,
  PRIMARY KEY (`id_Test`),
  INDEX `fk_Testy_Pytania1_idx` (`Pytania_idPytania` ASC),
  INDEX `fk_Testy_Odopwiedzi1_idx` (`Odopwiedzi_idPytania` ASC),
  CONSTRAINT `fk_Testy_Pytania1`
    FOREIGN KEY (`Pytania_idPytania`)
    REFERENCES `dbProjektor`.`Pytania` (`id_Pytania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Testy_Odopwiedzi1`
    FOREIGN KEY (`Odopwiedzi_idPytania`)
    REFERENCES `dbProjektor`.`Odopwiedzi` (`id_Odpowiedzi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Oceny`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Oceny` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Oceny` (
  `id_Ocena` INT NOT NULL AUTO_INCREMENT,
  `Procent_odpowiedzi` INT NOT NULL,
  PRIMARY KEY (`id_Ocena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Odpowiedz_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Odpowiedz_student` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Odpowiedz_student` (
  `id_odpo_test` INT NOT NULL AUTO_INCREMENT,
  `Studenci_id_Student` INT NOT NULL,
  `Opowiedz_wskazana` TINYINT NOT NULL,
  `Testy_id_Test` INT NOT NULL,
  `Oceny_id_Ocena` INT NOT NULL,
  PRIMARY KEY (`id_odpo_test`),
  INDEX `fk_Odp_Test_Studenci1_idx` (`Studenci_id_Student` ASC),
  INDEX `fk_Odpowiedz_student_Testy1_idx` (`Testy_id_Test` ASC),
  INDEX `fk_Odpowiedz_student_Oceny1_idx` (`Oceny_id_Ocena` ASC),
  CONSTRAINT `fk_Odp_Test_Studenci1`
    FOREIGN KEY (`Studenci_id_Student`)
    REFERENCES `dbProjektor`.`StudentWykladowca` (`id_StudentWykladowca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odpowiedz_student_Testy1`
    FOREIGN KEY (`Testy_id_Test`)
    REFERENCES `dbProjektor`.`Testy` (`id_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odpowiedz_student_Oceny1`
    FOREIGN KEY (`Oceny_id_Ocena`)
    REFERENCES `dbProjektor`.`Oceny` (`id_Ocena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Zajęcia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Zajęcia` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Zajęcia` (
  `id_Zajęcia` INT NOT NULL AUTO_INCREMENT,
  `id_Przedmiot` INT NOT NULL,
  `id_StudentGroup` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Obecnosc` TINYINT NOT NULL,
  `id_StudentWykladowca` INT NOT NULL,
  PRIMARY KEY (`id_Zajęcia`),
  INDEX `fk_Zajęcia_Przedmiot1_idx` (`id_Przedmiot` ASC),
  INDEX `fk_Zajęcia_StudentGroups1_idx` (`id_StudentGroup` ASC),
  INDEX `fk_Zajęcia_StudentWykladowca1_idx` (`id_StudentWykladowca` ASC),
  CONSTRAINT `fk_Zajęcia_Przedmiot1`
    FOREIGN KEY (`id_Przedmiot`)
    REFERENCES `dbProjektor`.`Przedmiot` (`id_Przedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajęcia_StudentGroups1`
    FOREIGN KEY (`id_StudentGroup`)
    REFERENCES `dbProjektor`.`StudentGroups` (`idStudentGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajęcia_StudentWykladowca1`
    FOREIGN KEY (`id_StudentWykladowca`)
    REFERENCES `dbProjektor`.`StudentWykladowca` (`id_StudentWykladowca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbProjektor`.`Zajecia_has_Testy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbProjektor`.`Zajecia_has_Testy` ;

CREATE TABLE IF NOT EXISTS `dbProjektor`.`Zajecia_has_Testy` (
  `id_Zajecia_has_Testy` INT NOT NULL AUTO_INCREMENT,
  `Zajęcia_id_Zajęcia` INT NOT NULL,
  `Testy_id_Test` INT NOT NULL,
  PRIMARY KEY (`id_Zajecia_has_Testy`),
  INDEX `fk_Zajecia_has_Testy_Zajęcia1_idx` (`Zajęcia_id_Zajęcia` ASC),
  INDEX `fk_Zajecia_has_Testy_Testy1_idx` (`Testy_id_Test` ASC),
  CONSTRAINT `fk_Zajecia_has_Testy_Zajęcia1`
    FOREIGN KEY (`Zajęcia_id_Zajęcia`)
    REFERENCES `dbProjektor`.`Zajęcia` (`id_Zajęcia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajecia_has_Testy_Testy1`
    FOREIGN KEY (`Testy_id_Test`)
    REFERENCES `dbProjektor`.`Testy` (`id_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
