-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 18:35:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbprojektor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbprojektor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbprojektor` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbprojektor` ;

-- -----------------------------------------------------
-- Table `dbprojektor`.`StudentGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`StudentGroups` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`StudentGroups` (
  `idStudentGroup` INT NOT NULL AUTO_INCREMENT,
  `RokRozpoczecia` DATE NOT NULL,
  `Nazwa_StudentGrups` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudentGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`StudentWykladowca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`StudentWykladowca` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`StudentWykladowca` (
  `id_StudentWykladowca` INT NOT NULL AUTO_INCREMENT,
  `id_StudentGroups` INT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Nr_Indexu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_StudentWykladowca`),
  INDEX `fk_Studenci_StudentGrups1_idx` (`id_StudentGroups` ASC),
  CONSTRAINT `fk_Studenci_StudentGrups1`
    FOREIGN KEY (`id_StudentGroups`)
    REFERENCES `dbprojektor`.`StudentGroups` (`idStudentGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Przedmiot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Przedmiot` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Przedmiot` (
  `id_Przedmiot` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Przedmiot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Pytania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Pytania` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Pytania` (
  `id_Pytania` INT NOT NULL,
  `Tekst Pytania` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Pytania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Odopwiedzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Odopwiedzi` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Odopwiedzi` (
  `id_Odpowiedzi` INT NOT NULL,
  `Odpowiedz` VARCHAR(45) NOT NULL,
  `Czy_prawidlowa` TINYINT NOT NULL,
  PRIMARY KEY (`id_Odpowiedzi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Testy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Testy` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Testy` (
  `id_Test` INT NOT NULL AUTO_INCREMENT,
  `Pytania_idPytania` INT NOT NULL,
  `Odopwiedzi_idPytania` INT NOT NULL,
  `Id_test_grupa` INT NOT NULL,
  PRIMARY KEY (`id_Test`),
  INDEX `fk_Testy_Pytania1_idx` (`Pytania_idPytania` ASC),
  INDEX `fk_Testy_Odopwiedzi1_idx` (`Odopwiedzi_idPytania` ASC),
  CONSTRAINT `fk_Testy_Pytania1`
    FOREIGN KEY (`Pytania_idPytania`)
    REFERENCES `dbprojektor`.`Pytania` (`id_Pytania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Testy_Odopwiedzi1`
    FOREIGN KEY (`Odopwiedzi_idPytania`)
    REFERENCES `dbprojektor`.`Odopwiedzi` (`id_Odpowiedzi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Oceny`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Oceny` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Oceny` (
  `id_Ocena` INT NOT NULL AUTO_INCREMENT,
  `Procent_odpowiedzi` INT NOT NULL,
  PRIMARY KEY (`id_Ocena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Odpowiedz_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Odpowiedz_student` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Odpowiedz_student` (
  `id_odpo_test` INT NOT NULL AUTO_INCREMENT,
  `Studenci_id_Student` INT NOT NULL,
  `Opowiedz_wskazana` TINYINT NOT NULL,
  `Testy_id_Test` INT NOT NULL,
  `Oceny_id_Ocena` INT NOT NULL,
  PRIMARY KEY (`id_odpo_test`),
  INDEX `fk_Odp_Test_Studenci1_idx` (`Studenci_id_Student` ASC),
  INDEX `fk_Odpowiedz_student_Testy1_idx` (`Testy_id_Test` ASC),
  INDEX `fk_Odpowiedz_student_Oceny1_idx` (`Oceny_id_Ocena` ASC),
  CONSTRAINT `fk_Odp_Test_Studenci1`
    FOREIGN KEY (`Studenci_id_Student`)
    REFERENCES `dbprojektor`.`StudentWykladowca` (`id_StudentWykladowca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odpowiedz_student_Testy1`
    FOREIGN KEY (`Testy_id_Test`)
    REFERENCES `dbprojektor`.`Testy` (`id_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odpowiedz_student_Oceny1`
    FOREIGN KEY (`Oceny_id_Ocena`)
    REFERENCES `dbprojektor`.`Oceny` (`id_Ocena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Zajecia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Zajecia` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Zajecia` (
  `id_Zajecia` INT NOT NULL AUTO_INCREMENT,
  `id_Przedmiot` INT NOT NULL,
  `id_StudentGroup` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Obecnosc` TINYINT NOT NULL,
  `id_StudentWykladowca` INT NOT NULL,
  PRIMARY KEY (`id_Zajecia`),
  INDEX `fk_Zajecia_Przedmiot1_idx` (`id_Przedmiot` ASC),
  INDEX `fk_Zajecia_StudentGroups1_idx` (`id_StudentGroup` ASC),
  INDEX `fk_Zajecia_StudentWykladowca1_idx` (`id_StudentWykladowca` ASC),
  CONSTRAINT `fk_Zajecia_Przedmiot1`
    FOREIGN KEY (`id_Przedmiot`)
    REFERENCES `dbprojektor`.`Przedmiot` (`id_Przedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajecia_StudentGroups1`
    FOREIGN KEY (`id_StudentGroup`)
    REFERENCES `dbprojektor`.`StudentGroups` (`idStudentGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajecia_StudentWykladowca1`
    FOREIGN KEY (`id_StudentWykladowca`)
    REFERENCES `dbprojektor`.`StudentWykladowca` (`id_StudentWykladowca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprojektor`.`Zajecia_has_Testy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbprojektor`.`Zajecia_has_Testy` ;

CREATE TABLE IF NOT EXISTS `dbprojektor`.`Zajecia_has_Testy` (
  `id_Zajecia_has_Testy` INT NOT NULL AUTO_INCREMENT,
  `Zajecia_id_Zajecia` INT NOT NULL,
  `Testy_id_Test` INT NOT NULL,
  PRIMARY KEY (`id_Zajecia_has_Testy`),
  INDEX `fk_Zajecia_has_Testy_Zajecia1_idx` (`Zajecia_id_Zajecia` ASC),
  INDEX `fk_Zajecia_has_Testy_Testy1_idx` (`Testy_id_Test` ASC),
  CONSTRAINT `fk_Zajecia_has_Testy_Zajecia1`
    FOREIGN KEY (`Zajecia_id_Zajecia`)
    REFERENCES `dbprojektor`.`Zajecia` (`id_Zajecia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zajecia_has_Testy_Testy1`
    FOREIGN KEY (`Testy_id_Test`)
    REFERENCES `dbprojektor`.`Testy` (`id_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
